/*
 * The MIT License
 * Copyright © 2025 Guilherme Kauã da Silva
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package tech.guilhermekaua.spigotboot.core.context.discovery;

import java.util.Map;

/**
 * Compile-time snapshot of classes in a given module that would otherwise be found by runtime
 * classpath scanning (e.g. {@code @Component} beans, {@code Module} implementations,
 * repositories, converters, placeholders, configs, etc.).
 *
 * <p>Generated by the {@code DiscoveryIndexProcessor} annotation processor and loaded at runtime
 * by {@code DiscoveryIndexReader}, which discovers per-class marker resources under
 * {@code META-INF/spigot-boot/discovery/}. The generated implementation resolves each listed class
 * by name through {@link DiscoveryIndexSupport} (so a class backed by an absent optional dependency
 * is skipped rather than crashing the index) and keeps the {@code .class} literals the Maven Shade
 * Plugin's {@code minimizeJar} reachability analyzer needs in a separate never-invoked method.
 *
 * <p>Keys are the string constants declared in {@link DiscoveryCategories}.
 */
public interface DiscoveryIndex {

    /**
     * @return an unmodifiable map from {@link DiscoveryCategories category key} to the classes
     * registered for that category. Implementations should return a consistent instance; callers
     * must not mutate it.
     */
    Map<String, Class<?>[]> entries();
}
