<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tech.guilhermekaua.spigot-boot</groupId>
        <artifactId>spigot-boot-inventory-api-parent</artifactId>
        <version>2.0.2</version>
    </parent>

    <name>${project.artifactId}</name>
    <description>Version selector that dispatches to the matching per-version NMS title updater for the inventory API.</description>
    <url>https://github.com/guikaua12/spigot-boot</url>
    <artifactId>spigot-boot-inventory-api-nms</artifactId>

    <dependencies>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.20.1-R0.1-20230917.004407-174</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_8_R3</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_12_R1</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_16_R3</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_17_R1</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_18_R2</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-inventory-api-nms-1_19_R3</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
