<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tech.guilhermekaua.spigot-boot</groupId>
        <artifactId>spigot-boot-versions-parent</artifactId>
        <version>2.0.2</version>
    </parent>

    <name>${project.artifactId}</name>
    <description>Thin consumer module for versioned custom entity support.</description>
    <url>https://github.com/guikaua12/spigot-boot</url>
    <artifactId>spigot-boot-versions</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencies>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-api</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-runtime</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_8_8</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_13_2</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_16_5</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_17_1</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_19_2</artifactId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>tech.guilhermekaua.spigot-boot</groupId>
            <artifactId>spigot-boot-versions-v1_21_11</artifactId>
            <version>2.0.2</version>
        </dependency>
    </dependencies>
</project>
